Clarify and try to fix location error (#21)
* If distribution is not found, explicitly show its name.

Otherwise you get a very uninformative error:

```
While:
  Installing test.
...
  File "/home/runner/eggs/zc.recipe.testrunner-3.1-py3.10.egg/zc/recipe/testrunner/__init__.py", line 48, in install
    test_paths = [ws.find(pkg_resources.Requirement.parse(spec)).location
  File "/home/runner/eggs/zc.recipe.testrunner-3.1-py3.10.egg/zc/recipe/testrunner/__init__.py", line 48, in <listcomp>
    test_paths = [ws.find(pkg_resources.Requirement.parse(spec)).location
AttributeError: 'NoneType' object has no attribute 'location'
```

See for example [this test run](https://github.com/collective/collective.exportimport/actions/runs/14313320340/job/40167791654#step:8:1178).

With an explicit error raised, I see which package gives a problem:

```
ValueError: Requirement not found in working set: plone.app.upgrade
```

* If distribution is not found, try its canonical name.

* Pragmatically except missing test coverage for distribution not found.

This is highly setuptools/buildout-version dependent.